name: tng_scriptgen_flutter_app
description: TNG Script Generator Mobile App

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
#